trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJo
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(enviroment)DeployJob
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment)DeployJob