trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, K8S Terraform Azure!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource-manager-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription daae98de-d83f-4119-8b18-233a5a778f4f
      az account show
      az group create --name terraform-backend-rg --location westeurope
      if ! az storage account check-name --name strgaccntcsamal05882 --query 'nameAvailable' --output tsv | grep -q 'true'; then
        echo "Storage account already exists."
      else
        echo "Creating storage account..."
        az storage account create \
          --name strgaccntcsamal05882 \
          --resource-group terraform-backend-rg \
          --sku Standard_RAGRS \
          --kind StorageV2 \
          --encryption-services blob \
          --access-tier hot \
          --allow-blob-public-access false \
          --https-only true \
          --min-tls-version TLS1_2
      fi

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'strgaccntcsamal05882'
    backendAzureRmContainerName: 'strgaccntcsamalcntnr'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
